---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.1/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  KS_RETRY_INTERVAL: "2m"
  KS_TIMEOUT: "5m"

  VAULT_PREFIX: "korg"

  TIMEZONE: "US/Central"
  CLUSTER_CIDR: "10.69.0.0/16"
  SERVICE_CIDR: "10.96.0.0/16"
  LAN_CIDR: "10.0.150.0/24"
  KUBE_DNS_ADDR: "10.96.0.10"
  CLUSTER_API_ADDR: "10.0.150.100"

  CLOUDFLARE_GATEWAY_ADDR: "10.0.150.10"
  CLUSTER_GATEWAY_ADDR: "10.0.150.11"
  CLUSTER_DNS_GATEWAY_ADDR: "10.0.150.12"

  CLUSTER_BGP_ASN: "65533"
  L2_NET_DEVICE: "eth0"

  CEPH_DEVICE_PATH_FILTER: "/dev/nvme0*"
  CEPH_CLUSTER_CIDR: "10.0.150.0/24"

  THEME_PARK_THEME: "space-gray"
  OPENEBS_HOSTPATH: "/var/mnt/lpp-0"

  GIT_REPO: "github.com/brunnels/home-ops"
  GIT_REPO_REF: "refs/heads/main"

  KOPIUR_SNAPSHOTCLASS: "csi-ceph-blockpool"
  KOPIUR_STORAGECLASS: "ceph-block"

  SVC_MQTT_ADDR: "10.0.150.14"
  SVC_PLEX_ADDR: "10.0.150.20"
  SVC_HAAS_ADDR: "10.0.150.21"
