---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/mcp-system/toolhive-mcp-servers/flux-mcp
  - ../../../base/mcp-system/toolhive-mcp-servers/kubectl-mcp
