---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homebox
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        HBOX_OIDC_CLIENT_ID: "{{ .HBOX_OIDC_CLIENT_ID }}"
        HBOX_OIDC_CLIENT_SECRET: "{{ .HBOX_OIDC_CLIENT_SECRET }}"
        HBOX_AUTH_API_KEY_PEPPER: "{{ .HBOX_AUTH_API_KEY_PEPPER }}"
  dataFrom:
    - extract:
        key: "${VAULT_PREFIX}/homebox"
