---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: "bootstrap/**/*"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
area/scripts:
  - changed-files:
      - any-glob-to-any-file: scripts/**/*
area/talos:
  - changed-files:
      - any-glob-to-any-file: talos/**/*
area/justfile:
  - changed-files:
      - any-glob-to-any-file:
          - .mise/**/*
area/mise:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*/mod.just"
          - justfile
cluster/main:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/kdev/**/*
cluster/utility:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/korg/**/*
