---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../clusters/korg
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./namespace.yaml
  - ../../common/observability/blackbox-exporter.yaml
  #- ../../common/observability/gatus-sidecar.yaml
  - ../../common/observability/grafana-instance.yaml
  - ../../common/observability/grafana-operator.yaml
  - ../../common/observability/kromgo.yaml
  - ../../common/observability/kube-prometheus-stack.yaml
  - ../../common/observability/silence-operator.yaml
  - ../../common/observability/smartctl-exporter.yaml
