---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${NAMESPACE}-pgbackrest
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: ${NAMESPACE}-pgbackrest
  storageClassName: nfs-${NAMESPACE}-pgbackrest
