---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name flood
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        TRANSMISSION__PEER_PORT: "{{ .AIRVPN_INBOUND_PORT }}"
  dataFrom:
    - extract:
        key: "${VAULT_PREFIX}/airvpn"
