---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs-hostpath
spec:
  chartRef:
    kind: OCIRepository
    name: openebs
  interval: 1h
  values:
    alloy:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    localpv-provisioner:
      analytics:
        enabled: false
      helperPod:
        image:
          registry: quay.io/
      localpv:
        basePath: &basePath ${OPENEBS_HOSTPATH}
        image:
          registry: quay.io/
      hostpathClass:
        basePath: *basePath
        enabled: true
        isDefaultClass: false
        name: openebs-hostpath
    loki:
      enabled: false
    lvm-localpv:
      enabled: false
    mayastor:
      enabled: false
    minio:
      enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
    preUpgradeHook:
      enabled: false
    zfs-localpv:
      enabled: false
