---
apiVersion: authelia.milas.dev/v1alpha2
kind: OIDCClient
metadata:
  name: ${APP}
  annotations:
    authelia.milas.dev/oidc-provider: ${NAMESPACE}/${APP}
spec:
  description: ${APP}
  grant_types:
    - authorization_code
    - refresh_token
  preconfigured_consent_duration: "30m"
  redirect_uris:
    - https://${APP}.${SECRET_DOMAIN}/oauth2/callback
  response_types:
    - code
  secret_ref:
    name: ${APP}
    fields:
      client_id: OIDC_CLIENT_ID
      client_secret: OIDC_CLIENT_SECRET
  scopes:
    - openid
    - offline_access
  token_endpoint:
    auth_method: client_secret_basic

  public: false
  authorization_policy: two_factor
  consent_mode: auto
  claims:
    policy:
      id_token: ["groups", "email", "email_verified", "alt_emails", "preferred_username", "name"]
