---
# yaml-language-server: $schema=https://json.schemastore.org/component.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./replicationdestination.yaml
  - ./replicationsource.yaml
secretGenerator:
  - name: letsencrypt-ca
    files:
      - ca.crt=../../base/security/authelia/resources/letsencrypt-certs.pem
generatorOptions:
  disableNameSuffixHash: true
