---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-ui
spec:
  dataFrom:
    - extract:
        key: ${VAULT_PREFIX}/toolhive
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        TOOLHIVE_OIDC_CLIENT_ID: "{{ .TOOLHIVE_OIDC_CLIENT_ID }}"
        TOOLHIVE_OIDC_CLIENT_SECRET: "{{ .TOOLHIVE_OIDC_CLIENT_SECRET }}"
        BETTER_AUTH_SECRET: "{{ .BETTER_AUTH_SECRET }}"
