- Communicate:
    - Discord:
        - icon: discord
          href: "https://discord.com/app"
    - Gmail:
        - icon: gmail
          href: "https://mail.google.com/mail/u/0/#inbox"
    - Google Calendar:
        - icon: google-calendar
          href: "https://calendar.google.com"
    - Google Voice:
        - icon: google-voice
          href: "https://voice.google.com"
- Git:
    - kubesearch:
        - icon: kubernetes-dashboard
          href: "https://kubesearch.dev/"
    - hope-ops:
        - icon: github
          href: "https://github.com/brunnels/hope-ops"
    - cluster-template:
        - icon: github
          href: "https://github.com/onedr0p/cluster-template"
