---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/inference.llmkube.dev/modelrouter_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: ModelRouter
metadata:
  name: ai3050-router
spec:
  backends:
    - displayName: Qwen3-8B-GGUF
      inferenceServiceRef:
        name: llama-nvidia-qwen3-8b-q4
      name: llama-qwen
      tier: local
      timeout: 5m
  defaultRouteStrategy: BackendNameMatch
  defaultRoute: llama-qwen
