---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/inference.llmkube.dev/model_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: qwen36-27b-q4
spec:
  source: https://huggingface.co/unsloth/Qwen3.6-27B-MTP-GGUF/resolve/main/Qwen3.6-27B-UD-Q4_K_XL.gguf
  format: gguf
  quantization: UD-Q4_K_XL
  hardware:
    accelerator: cuda
    gpu:
      enabled: true
      vendor: nvidia
      count: 0
      layers: -1
      resourceClaims:
        - name: gpu
          resourceClaimName: gpu-claim
