---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/inference.llmkube.dev/model_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: llama-nvidia-qwen3-8b-q4
spec:
  source: hf://unsloth/Qwen3-8B-GGUF
  files:
    - Qwen3-8B-UD-Q4_K_XL.gguf
  format: gguf
  quantization: UD-Q4_K_XL
  hardware:
    accelerator: cuda
    gpu:
      enabled: true
      vendor: nvidia
      count: 1
      layers: 8
