---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name romm
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        IGDB_CLIENT_ID: "{{ .IGDB_CLIENT_ID }}"
        IGDB_CLIENT_SECRET: "{{ .IGDB_CLIENT_SECRET }}"
        OIDC_CLIENT_ID: "{{ .ROMM_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .ROMM_OIDC_CLIENT_SECRET }}"
        ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"
        STEAMGRIDDB_API_KEY: "{{ .STEAMGRIDDB_API_KEY }}"
  dataFrom:
    - extract:
        key: "${VAULT_PREFIX}/igdb"
    - extract:
        key: "${VAULT_PREFIX}/romm"
    - extract:
        key: "${VAULT_PREFIX}/steamgriddb"
