---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app descheduler
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    deschedulerPolicy:
      profiles:
        - name: Default
          pluginConfig:
            - args:
                evictFailedBarePods: true
                evictLocalStoragePods: true
                evictSystemCriticalPods: true
              name: DefaultEvictor
            - args:
                excludeOwnerKinds:
                  - Job
                includingInitContainers: true
                minPodLifetimeSeconds: 1800
                reasons:
                  - ContainerStatusUnknown
                  - NodeAffinity
                  - NodeShutdown
                  - Terminated
                  - UnexpectedAdmissionError
              name: RemoveFailedPods
            - name: RemovePodsViolatingInterPodAntiAffinity
            - args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
              name: RemovePodsViolatingNodeAffinity
            - name: RemovePodsViolatingNodeTaints
            - name: RemovePodsViolatingTopologySpreadConstraint
          plugins:
            balance:
              enabled:
                - RemovePodsViolatingTopologySpreadConstraint
            deschedule:
              enabled:
                - RemoveFailedPods
                - RemovePodsViolatingInterPodAntiAffinity
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingNodeTaints
    deschedulerPolicyAPIVersion: descheduler/v1alpha2
    kind: Deployment
    leaderElection:
      enabled: true
    replicas: 2
    service:
      enabled: true
    serviceMonitor:
      enabled: true
