---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name open-webui
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        OAUTH_CLIENT_ID: "{{ .OPEN_WEBUI_OIDC_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPEN_WEBUI_OIDC_CLIENT_SECRET }}"
        WEBUI_SECRET_KEY: "{{ .OPEN_WEBUI_SECRET_KEY }}"
        DATABASE_URL: '{{ index . "pgbouncer-uri" }}'
        HF_TOKEN: "{{ .HF_TOKEN }}"
        OPENAI_API_KEY: "{{ .OMNIROUTE_API_KEY }}"
  dataFrom:
    - extract:
        key: ${VAULT_PREFIX}/omniroute
    - extract:
        key: ${VAULT_PREFIX}/open-webui
    - extract:
        key: ${NAMESPACE}-pguser-open-webui
      sourceRef:
        storeRef:
          kind: SecretStore
          name: "${NAMESPACE}-secrets"
    - extract:
        key: huggingface
