---
apiVersion: authelia.milas.dev/v1alpha2
kind: OIDCClient
metadata:
  name: &name open-webui
  annotations:
    authelia.milas.dev/oidc-provider: security/default
spec:
  description: Open Web-UI
  preconfigured_consent_duration: 1y
  redirect_uris:
    - https://chat.${SECRET_DOMAIN}/oauth2/callback
  response_types:
    - code
  secret_ref:
    name: *name
    fields:
      client_id: OPEN_WEBUI_OIDC_CLIENT_ID
      client_secret: OPEN_WEBUI_SECRET_KEY
  scopes:
    - email
    - openid
    - profile
    - groups
  # default should not be needed, but it is required for the operator to work issue: #6
  token_endpoint:
    auth_method: client_secret_basic
