---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app omniroute
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      omniroute:
        containers:
          app:
            image:
              repository: ghcr.io/diegosouzapw/omniroute
              tag: 3.8.49-web@sha256:a3155c4163ff3ee652868f04e5c34054e08f811da63110fe4ef0e1096d50312c
            env:
              NODE_ENV: production
              PORT: &port 20128
              REDIS_URL: redis://${NAMESPACE}-dragonfly:6379
              NEXT_PUBLIC_BASE_URL: &hostname https://omniroute.${SECRET_DOMAIN}
              LIVE_WS_HOST: 0.0.0.0
              LIVE_WS_ALLOWED_ORIGINS: *hostname
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: internal
            alerts:
              - type: pushover
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - omniroute.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /app/.build/next/cache
