---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app omniroute
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 100
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      omniroute:
        initContainers:
          copy-tmpfs:
            image:
              repository: ghcr.io/diegosouzapw/omniroute
              tag: main-web@sha256:6db75921dcad50cf81085a4733b492603ed8fdefcc8843e455a4f5f5b84327cf
            command:
              - sh
              - -c
              - find /tmp -mindepth 1 -maxdepth 1 -exec cp -r {} /tmpfs-mount/
                \; 2>/dev/null || true
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
        containers:
          app:
            image:
              repository: ghcr.io/diegosouzapw/omniroute
              tag: main-web@sha256:6db75921dcad50cf81085a4733b492603ed8fdefcc8843e455a4f5f5b84327cf
            env:
              NEXT_PUBLIC_BASE_URL: &hostname https://omniroute.${SECRET_DOMAIN}
              LIVE_WS_ALLOWED_ORIGINS: *hostname
              LIVE_WS_HOST: 0.0.0.0
              NODE_ENV: production
              OMNIROUTE_MEMORY_MB: 1024
              PORT: &port 20128
              REDIS_URL: redis://${NAMESPACE}-dragonfly:6379
              #CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY: 1
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
      tmpfs:
        type: emptyDir
        advancedMounts:
          omniroute:
            app:
              - path: /app/.build/next/cache
                subPath: cache
              - path: /tmp
                subPath: tmp
            copy-tmpfs:
              - path: /tmpfs-mount
                subPath: tmp
    route:
      app:
        hostnames:
          - omniroute.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    service:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: internal
            alerts:
              - type: pushover
        controller: *app
        ports:
          http:
            port: *port
