---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/virtualmcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway-internal
spec:
  groupRef:
    name: mcp-tools
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"
    optimizer:
      embeddingModel: toolhive-embed
      embeddingProvider: openai
      embeddingService: http://toolhive-embed:8080/v1
      embeddingServiceTimeout: 180s
  incomingAuth:
    type: anonymous
  outgoingAuth:
    source: discovered
  podTemplateSpec:
    spec:
      containers:
        - name: vmcp
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 2Gi
  #sessionStorage:
  #  address: redis://${NAMESPACE}-dragonfly.${NAMESPACE}:6379
  #  db: 0
  #  keyPrefix: "toolhive:vmcp:"
  #  provider: redis
  #telemetryConfigRef:
  #  name: prometheus
