---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  interval: 1h
  values:
    storageClass:
      create: true
      mountOptions:
        - nfsvers=4.1
        - nconnect=16
        - hard
        - noatime
        - nodiratime
        - rsize=1048576
        - wsize=1048576
      name: nfs-slow
      parameters:
        server: ${QNAP_HOSTNAME}
        share: "/appdata/${VAULT_PREFIX}-k8s"
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
