allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-model-cache
mountOptions:
  - nfsvers=4.1
  - nconnect=16
  - hard
  - noatime
  - nodiratime
  - rsize=1048576
  - wsize=1048576
parameters:
  server: ${QNAP_HOSTNAME}
  share: /appdata/shared-k8s
  subDir: model-cache
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
