---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: kubectl-mcp
spec:
  args:
    - --port=8080
    - --read-only
    - --stateless
  groupRef:
    name: mcp-tools
  image: ghcr.io/containers/kubernetes-mcp-server:latest
  mcpPort: 8000
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs
      securityContext:
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
      volumes:
        - name: tmpfs
          emptyDir:
            medium: Memory
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  serviceAccount: kubectl-mcp-readonly
  transport: streamable-http
