---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../clusters/kdev
  - ../../components/common
  - ../../components/kopiur/secret
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./namespace.yaml
  - ./ai-pgo-cluster.yaml
  - ./homebox.yaml
  - ./homebox-companion.yaml
  - ./kuberay-operator.yaml
  - ./open-webui.yaml
  - ./vllm-stack.yaml
