---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../clusters/kdev
  - ../../components/common
  - ../../components/kopiur/secret
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./namespace.yaml
  # namespace first
  - ./ai-pgo-cluster.yaml
  - ./dispatch.yaml
  - ./foreman-agents.yaml
  - ./foreman.yaml
  - ./homebox-companion.yaml
  - ./homebox.yaml
  #- ./litellm.yaml
  #- ./llmkube-models.yaml
  - ./llmkube.yaml
  - ./omniroute.yaml
  #- ./open-webui.yaml
