---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-registry
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/pgo-db-init
  dependsOn:
    - name: ai-pgo-cluster
    - name: toolhive-crds
  interval: 1h
  path: ./kubernetes/base/ai/toolhive-registry
  postBuild:
    substitute:
      APP: *app
      DB_NAMES: toolhive
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
