---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../clusters/korg
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./namespace.yaml
  - ../../common/storage/ceph-csi-drivers.yaml
  - ../../common/storage/kopia.yaml
  - ../../common/storage/kopiur.yaml
  - ../../common/storage/kopiur-repository.yaml
  - ../../common/storage/openebs-hostpath.yaml
  - ../../common/storage/rook-ceph-cluster.yaml
  - ../../common/storage/rook-ceph-operator.yaml
  - ../../common/storage/snapshot-controller.yaml
