---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP_SUBDOMAIN:-${APP}}-oidc
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${CLUSTER_SECRET_STORE:-akeyless-secret-store}
  target:
    name: ${APP_SUBDOMAIN:-${APP}}-oidc
  data:
    - secretKey: client-id
      remoteRef:
        key: ${VAULT_PREFIX}/${APP_SUBDOMAIN:-${APP}}
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: ${VAULT_PREFIX}/${APP_SUBDOMAIN:-${APP}}
        property: client-secret
