---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${APP}
  oidc:
    provider:
      issuer: "https://auth.${SECRET_DOMAIN}"
      authorizationEndpoint: "https://auth.${SECRET_DOMAIN}/api/oidc/authorization"
      tokenEndpoint: "https://auth.${SECRET_DOMAIN}/api/oidc/token"
    clientIDRef:
      name: "${APP}-oidc"
      key: client-id
    clientSecret:
      name: "${APP}-oidc"
      key: client-secret
    refreshToken: true
    cookieDomain: "${SECRET_DOMAIN}"
    cookieNames:
      idToken: ""
      accessToken: ""
    redirectURL: "https://${APP_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}/oauth2/callback"
    logoutPath: "${LOGOUT_PATH:-/logout}"
    scopes: ["openid", "profile", "email"]
    forwardAccessToken: false
    passThroughAuthHeader: false
