---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app direwolf-apps
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: direwolf-operator
    - name: nvidia-gpu-operator
      namespace: kube-system
    - name: openebs-hostpath
      namespace: storage
    - name: rook-ceph-cluster
      namespace: storage
  interval: 1h
  path: ./kubernetes/base/games/direwolf-apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
