---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 100
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 5.1.1@sha256:8f90c25c7ee2773112c76b209ba0c32f089ced996f0dd0683cdfeaf07df365f8
            env:
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd, sabnzbd.downloads, sabnzbd.downloads.svc,
                sabnzbd.downloads.svc.cluster,
                sabnzbd.downloads.svc.cluster.local, sabnzbd.${SECRET_DOMAIN}
              SABNZBD__PORT: &port 8080
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 5
                  httpGet:
                    path: /api?mode=version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
    persistence:
      config:
        existingClaim: *app
      applications:
        type: nfs
        path: /applications
        server: ${QNAP_HOSTNAME}
        globalMounts:
          - path: /media/applications
      downloads:
        type: nfs
        path: /downloads/${VAULT_PREFIX}/complete
        server: ${QNAP_HOSTNAME}
        globalMounts:
          - path: /downloads/complete
            subPath: *app
      games:
        type: nfs
        path: /games
        server: ${QNAP_HOSTNAME}
        globalMounts:
          - path: /media/games
      incomplete:
        type: nfs
        path: /downloads/${VAULT_PREFIX}/incomplete
        server: ${QNAP_HOSTNAME}
        globalMounts:
          - path: /incomplete
            subPath: *app
      misc:
        type: nfs
        path: /misc
        server: ${QNAP_HOSTNAME}
        globalMounts:
          - path: /media/misc
      tmp:
        type: emptyDir
    route:
      app:
        annotations:
          gethomepage.dev/description: NZB Download Client
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: *app
          gethomepage.dev/name: SABnzbd
          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_SABNZBD_TOKEN}}`}}"
          gethomepage.dev/widget.type: *app
          gethomepage.dev/widget.url: "http://sabnzbd.{{ .Release.Namespace }}:8080"
        hostnames:
          - "sabnzbd.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    service:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: internal
            alerts:
              - type: pushover
        ports:
          http:
            port: *port
