---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vpn-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      vpn-gateway:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/angelnu/pod-gateway
              tag: v1.13.0@sha256:a5b032e15f7570493977b330a5a86dcffebb807d35685ad803e47afb62d105f2
            command:
              - /bin/gateway_sidecar.sh
            resources: &resources
              limits:
                cpu: 175m
                memory: 192Mi
              requests:
                cpu: 100m
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add:
                  - NET_RAW
                  - NET_ADMIN

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
            env:
              DOT: off
              FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: off
              FIREWALL_VPN_INPUT_PORTS: "${INBOUND_PORTS}"
              HTTP_CONTROL_SERVER_ADDRESS: ":80"
              HTTP_CONTROL_SERVER_LOG: off
              TZ: "${TIMEZONE}"
              VPN_ENDPOINT_IP_VERSION: v4
              WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: 15s
            envFrom:
              - secretRef:
                  name: *app
            resources: *resources
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add:
                  - NET_ADMIN

          webhook:
            image:
              repository: ghcr.io/angelnu/gateway-admision-controller
              tag: v3.12.0@sha256:6f6ab596afd5fef0ca4648eadfb21cd37ba86fa5afa8b85edcc072976a61fbed
            env:
              TZ: "${TIMEZONE}"
            args:
              - --webhook-listen-address=:8080
              - --gateway=vpn-gateway-main.network.svc.cluster.local
              - --DNS=172.16.0.1
              - --configmapName=vpn-gateway
              - --setGatewayLabel=use-vpn-gateway
              - --setGatewayLabelValue=true
              - --tls-cert-file-path=/tls/tls-combined.pem
              - --tls-key-file-path=/tls/tls.key
              - --DNSPolicy=None
              - --initImage=ghcr.io/angelnu/pod-gateway:v1.13.0
              - --initImagePullPol=IfNotPresent
              - --initCmd=/bin/client_init.sh
              - --initMountPoint=/config
              - --sidecarImage=ghcr.io/angelnu/pod-gateway:v1.13.0
              - --sidecarImagePullPol=IfNotPresent
              - --sidecarCmd=/bin/client_sidecar.sh
              - --sidecarMountPoint=/config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 5
                  httpGet: &httpGet
                    path: /wh/health
                    port: &port 8080
                    scheme: HTTPS
                  initialDelaySeconds: 1
                  periodSeconds: 10
                  timeoutSeconds: 10

              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 30
                  httpGet: *httpGet
                  initialDelaySeconds: 0
                  periodSeconds: 1
                  timeoutSeconds: 1
            resources: *resources
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        initContainers:
          routes:
            image:
              repository: ghcr.io/angelnu/pod-gateway
              tag: v1.13.0@sha256:a5b032e15f7570493977b330a5a86dcffebb807d35685ad803e47afb62d105f2
            command:
              - /bin/gateway_init.sh
            securityContext:
              privileged: true
    defaultPodOptions:
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        type: configMap
        name: *app
        advancedMounts:
          vpn-gateway:
            app:
              - path: /config
                readOnly: true
            routes:
              - path: /config
                readOnly: true
      tls-cert:
        type: secret
        name: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-tls'
        advancedMounts:
          vpn-gateway:
            webhook:
              - path: /tls
                readOnly: true

    rawResources:
      # Create a selfsigned Issuer, in order to create a root CA certificate for signing certificates
      self-signed-issuer:
        manifest:
          apiVersion: cert-manager.io/v1
          kind: Issuer
          spec:
            selfSigned: {}
      # Generate a CA Certificate used to sign certificates
      ca-cert:
        manifest:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          spec:
            secretName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-ca'
            duration: 43800h # 5y
            issuerRef:
              name: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-self-signed-issuer'
              kind: Issuer
            commonName: 'ca.{{ include "bjw-s.common.lib.chart.names.fullname" $ }}.cert-manager'
            isCA: true
      # Create an Issuer that uses the above generated CA certificate to issue certs
      ca-issuer:
        manifest:
          apiVersion: cert-manager.io/v1
          kind: Issuer
          spec:
            ca:
              secretName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-ca'
      # Finally, generate a serving certificate for the manager to use
      cert:
        manifest:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          spec:
            secretName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-tls'
            duration: 8760h # 1y
            issuerRef:
              name: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-ca-issuer'
              kind: Issuer
            dnsNames:
              - '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
              - '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}.{{ .Release.Namespace }}'
              - '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}.{{ .Release.Namespace }}.svc'
      mutating-webhook-configuration:
        manifest:
          apiVersion: admissionregistration.k8s.io/v1
          kind: MutatingWebhookConfiguration
          metadata:
            annotations:
              cert-manager.io/inject-ca-from: network/vpn-gateway-webhook-tls
          webhooks:
            - admissionReviewVersions: ["v1", "v1beta1"]
              clientConfig:
                service:
                  name: vpn-gateway-webhook
                  namespace: network
                  path: /wh/mutating/setgateway
                  port: *port
              name: vpn-gateway.svc.cluster.local
              namespaceSelector:
                matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: In
                    values:
                      - downloads
              rules:
                - apiGroups: [""]
                  apiVersions: ["v1"]
                  operations: ["CREATE"]
                  resources: [pods]
                  scope: Namespaced
              sideEffects: None
              timeoutSeconds: 5

    #controllers:
    #  main:
    #    pod:
    #      annotations:
    #        configmap.reloader.stakater.com/reload: *name
    #        secret.reloader.stakater.com/reload: vpn-gateway
    #    containers:
    #      gluetun:
    #        enabled: true
    #        type: gluetun
    #        env:
    #          TZ: "${TIMEZONE}"
    #          FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: off
    #          DOT: off
    #          DOT_IPV6: off
    #          HTTP_CONTROL_SERVER_ADDRESS: ":80"
    #          HTTP_CONTROL_SERVER_LOG: off
    #          VPN_ENDPOINT_IP_VERSION: v4
    #          WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: 15s
    #          FIREWALL_VPN_INPUT_PORTS: "${INBOUND_PORTS}"
    #        envFrom:
    #          - secretRef:
    #              name: *app
    #        ports:
    #          - containerPort: 80
    #            name: gluetun
    #            protocol: TCP
    #        resources:
    #          requests:
    #            cpu: 100m
    #            memory: 64Mi
    #          limits:
    #            cpu: 175m
    #            memory: 192Mi
    #        securityContext:
    #          capabilities:
    #            add:
    #              - NET_ADMIN
    #global:
    #  fullnameOverride: *app
    #networkpolicies:
    #  main:
    #    enabled: false
    #publicPorts: ${PUBLIC_PORTS}
    #routed_namespaces: ${ROUTED_NAMESPACES}
    #service:
    #  main:
    #    controller: main
    #    type: ClusterIP
    #    clusterIP: None
    #    ports:
    #      http:
    #        port: 4789
    #        protocol: UDP
    #      gluetun:
    #        port: 80
    #        protocol: TCP
    #settings:
    #  NOT_ROUTED_TO_GATEWAY_CIDRS: "${CLUSTER_CIDR} ${SERVICE_CIDR}"
    #  VPN_BLOCK_OTHER_TRAFFIC: true
    #  VPN_LOCAL_CIDRS: "172.16.0.0/24 ${CLUSTER_CIDR} ${SERVICE_CIDR}"
    #  GATEWAY_ENABLE_DNSSEC: false
    #  VPN_INTERFACE: wg0
    #  VPN_TRAFFIC_PORT: 1637
    #webhook:
    #  namespaceSelector:
    #    type: custom
    #    custom:
    #      matchExpressions:
    #        - key: kubernetes.io/metadata.name
    #          operator: "In"
    #          values: ${ROUTED_NAMESPACES}
    #  # -- boolean: Default behavior for new PODs in the evaluated namespace
    #  # if true then the gatewayLabel and gatewayAnnotation below will not be utilized and the
    #  # gateway will be injected into every pod in the routed_namespaces
    #  gatewayDefault: false
    #  # -- boolean: gatewayLabel and gatewayAnnotation controls the label/annotation key of which the value,
    #  #   by default, must be 'true' on the pod in order for the gateway sidecar to be injected.
    #  gatewayLabel: use-vpn-gateway
    #  gatewayAnnotation: ""
    #  # -- string: When a value is configured for the gatewayLabelValue or setGatewayAnnotationValue,
    #  #   the value of the label and/or annotation set on the gatewayLabel or gatewayAnnotation
    #  #   must match the gatewayLabelValue or setGatewayAnnotationValue instead of the default 'true'.
    #  gatewayLabelValue: "true"
    #  gatewayAnnotationValue:
