---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grafana-mcp
spec:
  dataFrom:
    - extract:
        key: ${VAULT_PREFIX}/grafana
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USERNAME }}"
        GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
