---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana-mcp
spec:
  groupRef:
    name: mcp-tools
  image: docker.io/controlplaneio-fluxcd/mcp/grafana:latest
  mcpPort: 8000
  podTemplateSpec:
    spec:
      containers:
        - args:
            - run
            - --rm
            - -i
            - -e
            - GRAFANA_URL
            - -e
            - GRAFANA_AUTH
            - mcp/grafana
            - -t
            - sse
          env:
            GRAFANA_URL: "http://grafana-service.observability:3000"
          envFrom:
            - secretRef:
                name: &app
          name: mcp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
      securityContext:
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
  proxyMode: sse
  proxyPort: 8000
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  transport: sse
