---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: &app grafana-mcp
spec:
  groupRef:
    name: mcp-tools
  image: docker.io/controlplaneio-fluxcd/mcp/grafana:latest
  mcpPort: 8000
  podTemplateSpec:
    spec:
      containers:
        - args:
            - run
            - --rm
            - -i
            - -e
            - GRAFANA_URL
            - -e
            - GRAFANA_AUTH
            - mcp/grafana
            - -t
            - sse
          env:
            - name: GRAFANA_URL
              value: http://grafana-service.observability:3000
          name: mcp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
      securityContext:
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
  proxyMode: sse
  proxyPort: 8000
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  secrets:
    - key: GRAFANA_USERNAME
      name: *app
      targetEnvName: GRAFANA_USERNAME
    - key: GRAFANA_PASSWORD
      name: *app
      targetEnvName: GRAFANA_PASSWORD
  transport: sse
