---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: &app grafana-mcp
spec:
  args:
    - -t
    - streamable-http
    - --address
    - 0.0.0.0:8000
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.observability:3000
  envFrom:
    - secretRef:
        name: *app
  groupRef:
    name: mcp-tools
  image: mcp/grafana:latest
  mcpPort: 8000
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
      securityContext:
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  transport: streamable-http
