---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authelia-oidc-operator
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 1h
  #upgrade:
  #  crds: CreateReplace
  #  force: true
  values:
    controllers:
      controller_manager:
        containers:
          manager:
            image:
              repository: ghcr.io/brunnels/authelia-oidc-operator
              tag: pr-1
    rawResources:
      provider:
        forceRename: default
        manifest:
          apiVersion: authelia.milas.dev/v1alpha1
          kind: OIDCProvider
          spec:
            cors:
              allowed_origins_from_client_redirect_uris: true
