---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name home-assistant
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HASS_PIRATE_WEATHER_API_KEY: "{{ .HASS_PIRATE_WEATHER_API_KEY }}"
  dataFrom:
    - extract:
        key: "${VAULT_PREFIX}/hass"
