---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    defaultPodOptions:
      hostUsers: false
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 100
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.9.0@sha256:f795a47fa14a5b109cc524b7f7e8b3d9ab95665d0482d9a11b794b6ad8425baa
            env:
              HASS_URL: https://hass.${SECRET_DOMAIN}
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 2Gi
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.135.0@sha256:ccd326184d71efc5ebb94155eda7bb30153902342a35dbc8525450d81aa55012
            args:
              [
                "--auth",
                "none",
                "--disable-telemetry",
                "--disable-update-check",
                "--user-data-dir",
                "/config/.vscode",
                "--extensions-dir",
                "/config/.vscode",
                "--port",
                "8080",
                "/config",
              ]
            env:
              TZ: "${TIMEZONE}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
      cache:
        type: custom
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: openebs-hostpath
        globalMounts:
          - path: /config/.venv
      secrets:
        type: secret
        name: *app
        globalMounts:
          - path: /config/secrets.yaml
            subPath: secrets.yaml
            readOnly: true
      tmp:
        type: emptyDir
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            name: home-assistant
          gethomepage.dev/app: *app
          gethomepage.dev/description: Open Source Home Automation
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Automation
          gethomepage.dev/icon: *app
          gethomepage.dev/name: Home Assistant
          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_HASS_TOKEN}}`}}"
          gethomepage.dev/widget.type: homeassistant
          gethomepage.dev/widget.url: http://${SVC_HASS_ADDR}:8123
        hostnames:
          - hass.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
      code-server:
        annotations:
          gatus.home-operations.com/endpoint: |-
            name: hass-code
          gethomepage.dev/app: home-assistant
          gethomepage.dev/description: "Remote Development Machine"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Development
          gethomepage.dev/icon: code-server.png
          gethomepage.dev/name: "Code Server"
          gethomepage.dev/namespace: default
        hostnames:
          - hass-code.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: code-server
    service:
      app:
        type: LoadBalancer
        annotations:
          gatus.home-operations.com/endpoint: |-
            alerts:
              - type: pushover
            group: internal
            name: home-assistant
          lbipam.cilium.io/ips: ${SVC_HASS_ADDR}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
      code-server:
        annotations:
          gatus.home-operations.com/endpoint: |-
            alerts:
              - type: pushover
            group: internal
            name: hass-code
        ports:
          http:
            port: 8080
