---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.3.4@sha256:45d37a8be32fc1b2ebc64acc9ab219ca6226dcf04b4de0046d6c4e650b7a3022
            env:
              HASS_URL: "https://hass.${SECRET_DOMAIN}"
              TZ: "${TIMEZONE}"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 2Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.122.0@sha256:dbe5b1cf5c1f0edf47da6363fdadb89c456fb14b3d7e2a1545cabe20f5d7402a
            args:
              [
                "--auth",
                "none",
                "--disable-telemetry",
                "--disable-update-check",
                "--user-data-dir",
                "/config/.vscode",
                "--extensions-dir",
                "/config/.vscode",
                "--port",
                "8080",
                "/config"
              ]
            env:
              TZ: "${TIMEZONE}"
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      hostUsers: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        annotations:
          gatus.home-operations.com/endpoint: |
            group: internal
            alerts:
              - type: pushover
          lbipam.cilium.io/ips: ${SVC_HAAS_ADDR}
        externalTrafficPolicy: Local
        ports:
          http:
            port: &port 8123
          code-server:
            port: &codeserverPort 8080
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Automation
          gethomepage.dev/name: Home Assistant
          gethomepage.dev/icon: *app
          gethomepage.dev/app: *app
          gethomepage.dev/description: Open Source Home Automation
#          gethomepage.dev/widget.type: homeassistant
#          gethomepage.dev/widget.url: "http://${SVC_HAAS_ADDR}:8123"
#          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_HASS_TOKEN}}`}}"
        hostnames:
          - "hass.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
      code-server:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Development"
          gethomepage.dev/name: "Code Server"
          gethomepage.dev/app: home-assistant
          gethomepage.dev/namespace: default
          gethomepage.dev/icon: code-server.png
          gethomepage.dev/description: "Remote Development Machine"
        hostnames:
          - "hass-code.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *codeserverPort
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
      cache:
        type: custom
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: local-path
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        globalMounts:
          - path: /config/.venv
      secrets:
        type: secret
        name: *app
        globalMounts:
          - path: /config/secrets.yaml
            subPath: secrets.yaml
            readOnly: true
      tmp:
        type: emptyDir
