---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ai-gateway-crds
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ai-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  dependsOn:
    - name: ai-gateway-crds
  interval: 1h
  values:
    global:
      imageRegistry: mirror.gcr.io
