---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app litellm
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/dragonfly
    - ../../../components/pgo-db-init
  dependsOn:
    - name: ai-pgo-cluster
    - name: dragonfly-operator
      namespace: database
    - name: litellm-operator
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  interval: 1h
  path: ./kubernetes/base/ai/litellm
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 1Gi
      KOPIUR_ACCESSMODES: ReadWriteMany
      KOPIUR_STORAGECLASS: ceph-filesystem
      KOPIUR_SNAPSHOTCLASS: csi-ceph-filesystem
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
