---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/miroir.home-operations.com/miroirnodegroup_v1alpha1.json
apiVersion: miroir.home-operations.com/v1alpha1
kind: MiroirNodeGroup
metadata:
  name: default
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/arch: amd64
  template:
    pools:
      - name: miroir-local
        loopfile:
          baseDir: /var/mnt/miroir-local
      - name: miroir
        lvmthin:
          device: /dev/nvme0n1
