---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: *name
            items:
              - key: services.yaml
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CF_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CF_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CF_API_TOKEN }}"
        HOMEPAGE_VAR_QNAP_USERNAME: "{{ .QNAP_RO_USER }}"
        HOMEPAGE_VAR_QNAP_PASSWORD: "{{ .QNAP_RO_PASS }}"
        ## Home
#        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HASS_TOKEN }}"
        ## Downloads
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"
        ## Media
#        HOMEPAGE_VAR_BAZARR_TOKEN: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_OVERSEERR_TOKEN: "{{ .OVERSEERR_API_KEY }}"
#        HOMEPAGE_VAR_JELLYFIN_TOKEN: "{{ .JELLYFIN_HOMEPAGE_API_KEY }}"
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .LIDARR_API_KEY }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_TAUTULLI_TOKEN: "{{ .TAUTULLI_API_KEY }}"
        ## Observability
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        HOMEPAGE_VAR_PEANUT_TOKEN: "{{ .PEANUT_API_PASSWORD }}"
        ## Security
        ## Location
        HOMEPAGE_VAR_LATITUDE: "{{ .HASS_LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        ## Linkwarden
#        HOMEPAGE_VAR_LINKWARDEN_TOKEN: "{{ .LINKWARDEN_API_KEY }}"

  dataFrom:
#    - extract:
#        key: "${VAULT_PREFIX}/bazarr"
    - extract:
        key: "${VAULT_PREFIX}/cloudflare"
    - extract:
        key: "${VAULT_PREFIX}/grafana"
    - extract:
        key: "${VAULT_PREFIX}/hass"
#    - extract:
#        key: "${VAULT_PREFIX}/jellyfin"
    - extract:
        key: "${VAULT_PREFIX}/lidarr"
#    - extract:
#        key: "${VAULT_PREFIX}/linkwarden"
    - extract:
        key: "${VAULT_PREFIX}/opnsense"
    - extract:
        key: "${VAULT_PREFIX}/overseerr"
    - extract:
        key: "${VAULT_PREFIX}/peanut"
    - extract:
        key: "${VAULT_PREFIX}/plex"
    - extract:
        key: "${VAULT_PREFIX}/prowlarr"
    - extract:
        key: "${VAULT_PREFIX}/qnap"
    - extract:
        key: "${VAULT_PREFIX}/qnap-backup"
    - extract:
        key: "${VAULT_PREFIX}/radarr"
    - extract:
        key: "${VAULT_PREFIX}/sabnzbd"
    - extract:
        key: "${VAULT_PREFIX}/sonarr"
    - extract:
        key: "${VAULT_PREFIX}/tautulli"
