---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      homepage:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image: &image
              repository: ghcr.io/gethomepage/homepage
              tag: v1.10.1@sha256:0b596092c0b55fe4c65379a428a3fe90bd192f10d1b07d189a34fe5fabe7eedb
            env:
              TZ: "${TIMEZONE}"
              HOMEPAGE_ALLOWED_HOSTS: "*"
              NODE_OPTIONS: "--max-http-header-size=65536"
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthcheck
                    port: &port 3000
            resources: &resources
              requests:
                cpu: 15m
                memory: 128Mi
              limits:
                memory: 768Mi
        initContainers:
          init:
            image: *image
            command: ["sh", "-c", "cp -r /app/.next/server/pages/* /pages"]
            resources: *resources
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            group: internal
            alerts:
              - type: pushover
        ports:
          http:
            port: *port
    serviceAccount:
      homepage: {}
    rbac:
      roles:
        app:
          forceRename: *app
          type: ClusterRole
          rules:
            - apiGroups: [""]
              resources: ["namespaces", "nodes", "pods"]
              verbs: ["get", "list"]

            - apiGroups: ["gateway.networking.k8s.io"]
              resources: ["httproutes", "gateways"]
              verbs: ["get", "list"]

            - apiGroups: ["metrics.k8s.io"]
              resources: ["nodes", "pods"]
              verbs: ["get", "list"]

            - apiGroups: ["apiextensions.k8s.io"]
              resources: ["customresourcedefinitions/status"]
              verbs: ["get"]
      bindings:
        app:
          forceRename: *app
          type: ClusterRoleBinding
          roleRef:
            kind: ClusterRole
            name: *app
            apiGroup: rbac.authorization.k8s.io
          subjects:
            - kind: ServiceAccount
              name: *app
              namespace: default
    route:
      app:
        hostnames:
          - "homepage.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        type: emptyDir
        advancedMounts:
          homepage:
            init:
              - path: /pages
                subPath: pages
            app:
              - path: /app/config
                subPath: config
              - path: /app/.next/server/pages
                subPath: pages
      config-settings:
        type: configMap
        name: *app
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
      logs:
        type: emptyDir
        sizeLimit: 100Mi
        globalMounts:
          - path: /app/config/logs
