---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authelia
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/dragonfly-cluster
    - ../../../components/pgo-db-init
  dependsOn:
    - name: dragonfly-operator
      namespace: database
    - name: security-pgo-cluster
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      inProgress: status.phase != "Ready"
      current: status.phase == "Ready"
    #- apiVersion: batch/v1
    #  kind: Job
    #  inProgress: status.succeeded == 0
    #  current: status.succeeded != 0
  interval: 1h
  path: ./kubernetes/base/security/authelia
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
