---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vllm-stack
spec:
  chart:
    spec:
      chart: *app
      version: 0.1.11
      sourceRef:
        kind: HelmRepository
        name: *app
  interval: 1h
  upgrade:
    force: true
  values:
    servingEngineSpec:
      runtimeClassName: nvidia
      strategy:
        type: Recreate
      modelSpec:
        #- name: "distilgpt2-raycluster"
        #  repository: "vllm/vllm-openai"
        #  tag: "latest"
        #  modelURL: "distilbert/distilgpt2"
        #
        #  replicaCount: 1
        #
        #  requestCPU: 1
        #  requestMemory: "20Gi"
        #  requestGPU: 1
        #
        #  vllmConfig:
        #    tensorParallelSize: 1
        #    pipelineParallelSize: 2
        #
        #  shmSize: "20Gi"
        #
        #  raySpec:
        #    enabled: true
        #    headNode:
        #      requestCPU: 1
        #      requestMemory: "20Gi"
        #      requestGPU: 1

        - name: qwen25-vl-3b-instruct-awq
          repository: vllm/vllm-openai
          tag: latest
          modelURL: Qwen/Qwen2.5-3B-Instruct-AWQ

          replicaCount: 1

          requestCPU: 4
          requestMemory: 16Gi
          requestGPU: 1

          pvcStorage: 50Gi
          pvcAccessMode:
            - ReadWriteOnce
          storageClass: openebs-hostpath
          env:
            - name: PYTORCH_CUDA_ALLOC_CONF
              value: "expandable_segments:True"
          vllmConfig:
            #tensorParallelSize: 1
            #pipelineParallelSize: 3
            #enablePrefixCaching: true
            #maxModelLen: 4096
            dtype: bfloat16
            extraArgs:
              - "--quantization"
              - "awq"
              - "--reasoning-parser"
              - "qwen3"
              - "--gpu-memory-utilization"
              - "0.9"
              - "--enforce-eager"
              - "--max-num-seqs"
              - "32"
              - "--enable-auto-tool-choice"
              - "--tool-call-parser"
              - "qwen3_xml"

          #lmcacheConfig:
          #  enabled: true
          #  cpuOffloadingBufferSize: 20

          hf_token:
            secretName: *app
            secretKey: HF_TOKEN

          #raySpec:
          #  enabled: true
          #  headNode:
          #    requestCPU: 2
          #    requestMemory: 16Gi
          #    requestGPU: 1

          #shmSize: 16Gi

    #cacheserverSpec:
    #  replicaCount: 1
    #  containerPort: 8080
    #  servicePort: 81
    #  serde: naive
    #  repository: lmcache/vllm-openai
    #  tag: latest-nightly
    #  resources:
    #    requests:
    #      cpu: 2
    #      memory: 2G
    #    limits:
    #      cpu: 2
    #      memory: 10G
    #  labels:
    #    environment: cacheserver
    #    release: cacheserver

    routerSpec:
      enableRouter: true
      route:
        main:
          enabled: true
          hostnames:
            - "llm-api.${SECRET_DOMAIN}"
          parentRefs:
            - name: envoy-internal
              namespace: network
          matches:
            - path:
                type: PathPrefix
                value: /
