---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vllm-stack
spec:
  chart:
    spec:
      chart: *app
      version: 0.1.11
      sourceRef:
        kind: HelmRepository
        name: *app
  interval: 1h
  values:
    servingEngineSpec:
      runtimeClassName: nvidia
      strategy:
        type: Recreate
      modelSpec:
        - name: qwen35
          repository: lmcache/vllm-openai
          tag: latest-nightly
          modelURL: Qwen/Qwen3.5-4B

          replicaCount: 1

          requestCPU: 4
          requestMemory: 16Gi
          requestGPU: 1

          pvcStorage: 50Gi
          pvcAccessMode:
            - ReadWriteOnce
          storageClass: openebs-hostpath

          vllmConfig:
            #  enablePrefixCaching: true
            maxModelLen: 4096
            dtype: bfloat16
            gpuMemoryUtilization: 0.9
            extraArgs:
              - --enforce-eager

          #lmcacheConfig:
          #  enabled: true
          #  cpuOffloadingBufferSize: 20

          hf_token:
            secretName: *app
            secretKey: HF_TOKEN

    #cacheserverSpec:
    #  replicaCount: 1
    #  containerPort: 8080
    #  servicePort: 81
    #  serde: naive
    #  repository: lmcache/vllm-openai
    #  tag: latest-nightly
    #  resources:
    #    requests:
    #      cpu: 2
    #      memory: 2G
    #    limits:
    #      cpu: 2
    #      memory: 10G
    #  labels:
    #    environment: cacheserver
    #    release: cacheserver

    routerSpec:
      enableRouter: true
      route:
        main:
          enabled: true
          hostnames:
            - "llm-api.${SECRET_DOMAIN}"
          parentRefs:
            - name: envoy-internal
              namespace: network
          matches:
            - path:
                type: PathPrefix
                value: /
