---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-sonarr
spec:
  dataFrom:
    - extract:
        key: ${VAULT_PREFIX}/sonarr
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-radarr
spec:
  dataFrom:
    - extract:
        key: ${VAULT_PREFIX}/radarr
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-prowlarr
spec:
  dataFrom:
    - extract:
        key: ${VAULT_PREFIX}/prowlarr
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
